// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TopZoneContext))]
    [Migration("20260406160919_UpdateTableApplicationUser")]
    partial class UpdateTableApplicationUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.GroupSpecification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GroupSpecifications");
                });

            modelBuilder.Entity("Domain.Entities.ImagesProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("SubProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubProductId");

                    b.ToTable("ImagesProduct");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Domain.Entities.Specification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Specifications");
                });

            modelBuilder.Entity("Domain.Entities.SpecificationSubProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdSpecification")
                        .HasColumnType("int");

                    b.Property<int>("IdSubProduct")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdSpecification");

                    b.HasIndex("IdSubProduct");

                    b.ToTable("SpecificationSubProducts");
                });

            modelBuilder.Entity("Domain.Entities.SubProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdProduct");

                    b.ToTable("SubProducts");
                });

            modelBuilder.Entity("Domain.Entities.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MainTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MainTypeId");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("Domain.Entities.TypeProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<int>("IdType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdType");

                    b.ToTable("TypeProducts");
                });

            modelBuilder.Entity("Domain.Entities.ImagesProduct", b =>
                {
                    b.HasOne("Domain.Entities.SubProduct", null)
                        .WithMany("ImagesProduct")
                        .HasForeignKey("SubProductId");
                });

            modelBuilder.Entity("Domain.Entities.Specification", b =>
                {
                    b.HasOne("Domain.Entities.GroupSpecification", "GroupSpecification")
                        .WithMany("Specifications")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupSpecification");
                });

            modelBuilder.Entity("Domain.Entities.SpecificationSubProduct", b =>
                {
                    b.HasOne("Domain.Entities.Specification", "Specification")
                        .WithMany("SpecificationSubProducts")
                        .HasForeignKey("IdSpecification")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.SubProduct", "SubProduct")
                        .WithMany("SpecificationSubProducts")
                        .HasForeignKey("IdSubProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specification");

                    b.Navigation("SubProduct");
                });

            modelBuilder.Entity("Domain.Entities.SubProduct", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("SubProducts")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Type", b =>
                {
                    b.HasOne("Domain.Entities.Type", "MainType")
                        .WithMany("SubTypes")
                        .HasForeignKey("MainTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MainType");
                });

            modelBuilder.Entity("Domain.Entities.TypeProduct", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("TypeProducts")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Type", "Type")
                        .WithMany("TypeProducts")
                        .HasForeignKey("IdType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.Entities.GroupSpecification", b =>
                {
                    b.Navigation("Specifications");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Navigation("SubProducts");

                    b.Navigation("TypeProducts");
                });

            modelBuilder.Entity("Domain.Entities.Specification", b =>
                {
                    b.Navigation("SpecificationSubProducts");
                });

            modelBuilder.Entity("Domain.Entities.SubProduct", b =>
                {
                    b.Navigation("ImagesProduct");

                    b.Navigation("SpecificationSubProducts");
                });

            modelBuilder.Entity("Domain.Entities.Type", b =>
                {
                    b.Navigation("SubTypes");

                    b.Navigation("TypeProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
